#pin_mappings.py - utility script to help map NEEK HSMC pins to SOC boards

#generated from golden hardware design
#grep hsma bts_xcvr.qsf | grep PIN | cut -d " " -f 2,4 | perl -pe 's/^([^\s]+)\s+([^\s]+$)/["\1", "\2"],/'
soc_pins = [["PIN_H4", "hsma_tx_p[3]"],
["PIN_K4", "hsma_tx_p[2]"],
["PIN_M4", "hsma_tx_p[1]"],
["PIN_P4", "hsma_tx_p[0]"],
["PIN_H3", "hsma_tx_n[3]"],
["PIN_K3", "hsma_tx_n[2]"],
["PIN_M3", "hsma_tx_n[1]"],
["PIN_P3", "hsma_tx_n[0]"],
["PIN_C12", "hsma_tx_d_p[16]"],
["PIN_B13", "hsma_tx_d_p[15]"],
["PIN_C10", "hsma_tx_d_p[14]"],
["PIN_C8", "hsma_tx_d_p[13]"],
["PIN_A9", "hsma_tx_d_p[12]"],
["PIN_C7", "hsma_tx_d_p[11]"],
["PIN_A6", "hsma_tx_d_p[10]"],
["PIN_D5", "hsma_tx_d_p[9]"],
["PIN_A4", "hsma_tx_d_p[8]"],
["PIN_C3", "hsma_tx_d_p[7]"],
["PIN_B2", "hsma_tx_d_p[6]"],
["PIN_D2", "hsma_tx_d_p[5]"],
["PIN_E1", "hsma_tx_d_p[4]"],
["PIN_E3", "hsma_tx_d_p[3]"],
["PIN_E4", "hsma_tx_d_p[2]"],
["PIN_D6", "hsma_tx_d_p[1]"],
["PIN_E8", "hsma_tx_d_p[0]"],
["PIN_B11", "hsma_tx_d_n[16]"],
["PIN_A13", "hsma_tx_d_n[15]"],
["PIN_C9", "hsma_tx_d_n[14]"],
["PIN_B8", "hsma_tx_d_n[13]"],
["PIN_A8", "hsma_tx_d_n[12]"],
["PIN_B7", "hsma_tx_d_n[11]"],
["PIN_A5", "hsma_tx_d_n[10]"],
["PIN_C4", "hsma_tx_d_n[9]"],
["PIN_A3", "hsma_tx_d_n[8]"],
["PIN_B3", "hsma_tx_d_n[7]"],
["PIN_B1", "hsma_tx_d_n[6]"],
["PIN_C2", "hsma_tx_d_n[5]"],
["PIN_D1", "hsma_tx_d_n[4]"],
["PIN_E2", "hsma_tx_d_n[3]"],
["PIN_D4", "hsma_tx_d_n[2]"],
["PIN_C5", "hsma_tx_d_n[1]"],
["PIN_D7", "hsma_tx_d_n[0]"],
["PIN_AH2", "hsma_sda"],
["PIN_AA12", "hsma_scl"],
["PIN_J2", "hsma_rx_p[3]"],
["PIN_L2", "hsma_rx_p[2]"],
["PIN_N2", "hsma_rx_p[1]"],
["PIN_R2", "hsma_rx_p[0]"],
["PIN_J1", "hsma_rx_n[3]"],
["PIN_L1", "hsma_rx_n[2]"],
["PIN_N1", "hsma_rx_n[1]"],
["PIN_R1", "hsma_rx_n[0]"],
["PIN_F15", "hsma_rx_d_p[16]"],
["PIN_C13", "hsma_rx_d_p[15]"],
["PIN_F13", "hsma_rx_d_p[14]"],
["PIN_E12", "hsma_rx_d_p[13]"],
["PIN_D11", "hsma_rx_d_p[12]"],
["PIN_E9", "hsma_rx_d_p[11]"],
["PIN_B6", "hsma_rx_d_p[10]"],
["PIN_F11", "hsma_rx_d_p[9]"],
["PIN_F9", "hsma_rx_d_p[8]"],
["PIN_G10", "hsma_rx_d_p[7]"],
["PIN_H8", "hsma_rx_d_p[6]"],
["PIN_J7", "hsma_rx_d_p[5]"],
["PIN_G12", "hsma_rx_d_p[4]"],
["PIN_K7", "hsma_rx_d_p[3]"],
["PIN_J10", "hsma_rx_d_p[2]"],
["PIN_K12", "hsma_rx_d_p[1]"],
["PIN_H14", "hsma_rx_d_p[0]"],
["PIN_F14", "hsma_rx_d_n[16]"],
["PIN_B12", "hsma_rx_d_n[15]"],
["PIN_E13", "hsma_rx_d_n[14]"],
["PIN_D12", "hsma_rx_d_n[13]"],
["PIN_D10", "hsma_rx_d_n[12]"],
["PIN_D9", "hsma_rx_d_n[11]"],
["PIN_B5", "hsma_rx_d_n[10]"],
["PIN_E11", "hsma_rx_d_n[9]"],
["PIN_F8", "hsma_rx_d_n[8]"],
["PIN_F10", "hsma_rx_d_n[7]"],
["PIN_G8", "hsma_rx_d_n[6]"],
["PIN_H7", "hsma_rx_d_n[5]"],
["PIN_G11", "hsma_rx_d_n[4]"],
["PIN_K8", "hsma_rx_d_n[3]"],
["PIN_J9", "hsma_rx_d_n[2]"],
["PIN_J12", "hsma_rx_d_n[1]"],
["PIN_G13", "hsma_rx_d_n[0]"],
["PIN_AD12", "hsma_prsntn"],
["PIN_AG1", "hsma_d[3]"],
["PIN_AG7", "hsma_d[2]"],
["PIN_AF8", "hsma_d[1]"],
["PIN_AF9", "hsma_d[0]"],
["PIN_A10", "hsma_clk_out0"],
["PIN_E7", "hsma_clk_out_p2"],
["PIN_E6", "hsma_clk_out_n2"],
["PIN_K14", "hsma_clk_in0"],
["PIN_H15", "hsma_clk_in_p2"],
["PIN_G15", "hsma_clk_in_n2"],
["PIN_AJ2", "hsma_clk_out_p1"],
["PIN_AC12", "hsma_clk_out_n1"],
["PIN_AG2", "hsma_clk_in_p1"],
["PIN_AH3", "hsma_clk_in_n1"]]

#manually typed in from schematics
soc_hsmc = [["hsma_tx_p[3]", "hsmc_17"],
["hsma_tx_p[2]", "hsmc_21"],
["hsma_tx_p[1]", "hsmc_25"],
["hsma_tx_p[0]", "hsmc_29"],
["hsma_tx_n[3]", "hsmc_19"],
["hsma_tx_n[2]", "hsmc_23"],
["hsma_tx_n[1]", "hsmc_27"],
["hsma_tx_n[0]", "hsmc_31"],
["hsma_tx_d_p[16]", "hsmc_149"],
["hsma_tx_d_p[15]", "hsmc_143"],
["hsma_tx_d_p[14]", "hsmc_137"],
["hsma_tx_d_p[13]", "hsmc_131"],
["hsma_tx_d_p[12]", "hsmc_125"],
["hsma_tx_d_p[11]", "hsmc_119"],
["hsma_tx_d_p[10]", "hsmc_113"],
["hsma_tx_d_p[9]", "hsmc_107"],
["hsma_tx_d_p[8]", "hsmc_101"],
["hsma_tx_d_p[7]", "hsmc_89"],
["hsma_tx_d_p[6]", "hsmc_83"],
["hsma_tx_d_p[5]", "hsmc_77"],
["hsma_tx_d_p[4]", "hsmc_71"],
["hsma_tx_d_p[3]", "hsmc_65"],
["hsma_tx_d_p[2]", "hsmc_59"],
["hsma_tx_d_p[1]", "hsmc_53"],
["hsma_tx_d_p[0]", "hsmc_47"],
["hsma_tx_d_n[16]", "hsmc_151"],
["hsma_tx_d_n[15]", "hsmc_145"],
["hsma_tx_d_n[14]", "hsmc_139"],
["hsma_tx_d_n[13]", "hsmc_133"],
["hsma_tx_d_n[12]", "hsmc_127"],
["hsma_tx_d_n[11]", "hsmc_121"],
["hsma_tx_d_n[10]", "hsmc_115"],
["hsma_tx_d_n[9]", "hsmc_109"],
["hsma_tx_d_n[8]", "hsmc_103"],
["hsma_tx_d_n[7]", "hsmc_91"],
["hsma_tx_d_n[6]", "hsmc_85"],
["hsma_tx_d_n[5]", "hsmc_79"],
["hsma_tx_d_n[4]", "hsmc_73"],
["hsma_tx_d_n[3]", "hsmc_67"],
["hsma_tx_d_n[2]", "hsmc_61"],
["hsma_tx_d_n[1]", "hsmc_55"],
["hsma_tx_d_n[0]", "hsmc_49"],
["hsma_sda", "hsmc_33"],
["hsma_scl", "hsmc_34"],
["hsma_rx_p[3]", "hsmc_18"],
["hsma_rx_p[2]", "hsmc_22"],
["hsma_rx_p[1]", "hsmc_26"],
["hsma_rx_p[0]", "hsmc_30"],
["hsma_rx_n[3]", "hsmc_20"],
["hsma_rx_n[2]", "hsmc_24"],
["hsma_rx_n[1]", "hsmc_28"],
["hsma_rx_n[0]", "hsmc_32"],
["hsma_rx_d_p[16]", "hsmc_150"],
["hsma_rx_d_p[15]", "hsmc_144"],
["hsma_rx_d_p[14]", "hsmc_138"],
["hsma_rx_d_p[13]", "hsmc_132"],
["hsma_rx_d_p[12]", "hsmc_126"],
["hsma_rx_d_p[11]", "hsmc_120"],
["hsma_rx_d_p[10]", "hsmc_114"],
["hsma_rx_d_p[9]", "hsmc_108"],
["hsma_rx_d_p[8]", "hsmc_102"],
["hsma_rx_d_p[7]", "hsmc_90"],
["hsma_rx_d_p[6]", "hsmc_84"],
["hsma_rx_d_p[5]", "hsmc_78"],
["hsma_rx_d_p[4]", "hsmc_72"],
["hsma_rx_d_p[3]", "hsmc_66"],
["hsma_rx_d_p[2]", "hsmc_60"],
["hsma_rx_d_p[1]", "hsmc_54"],
["hsma_rx_d_p[0]", "hsmc_48"],
["hsma_rx_d_n[16]", "hsmc_152"],
["hsma_rx_d_n[15]", "hsmc_146"],
["hsma_rx_d_n[14]", "hsmc_140"],
["hsma_rx_d_n[13]", "hsmc_134"],
["hsma_rx_d_n[12]", "hsmc_128"],
["hsma_rx_d_n[11]", "hsmc_122"],
["hsma_rx_d_n[10]", "hsmc_116"],
["hsma_rx_d_n[9]", "hsmc_110"],
["hsma_rx_d_n[8]", "hsmc_104"],
["hsma_rx_d_n[7]", "hsmc_92"],
["hsma_rx_d_n[6]", "hsmc_86"],
["hsma_rx_d_n[5]", "hsmc_80"],
["hsma_rx_d_n[4]", "hsmc_74"],
["hsma_rx_d_n[3]", "hsmc_68"],
["hsma_rx_d_n[2]", "hsmc_62"],
["hsma_rx_d_n[1]", "hsmc_56"],
["hsma_rx_d_n[0]", "hsmc_50"],
["hsma_prsntn", "hsmc_160"],
["hsma_d[3]", "hsmc_44"],
["hsma_d[2]", "hsmc_43"],
["hsma_d[1]", "hsmc_42"],
["hsma_d[0]", "hsmc_41"],
["hsma_clk_out0", "hsmc_39"],
["hsma_clk_out_p2", "hsmc_155"],
["hsma_clk_out_n2", "hsmc_157"],
["hsma_clk_in0", "hsmc_40"],
["hsma_clk_in_p2", "hsmc_156"],
["hsma_clk_in_n2", "hsmc_158"],
["hsma_clk_out_p1", "hsmc_95"],
["hsma_clk_out_n1", "hsmc_97"],
["hsma_clk_in_p1", "hsmc_96"],
["hsma_clk_in_n1", "hsmc_98"]]

#manually typed in from schematics
hsmc_mult = [
["hsmc_34",		"hc_i2c_sclk"],
["hsmc_33", 	"hc_i2c_sdat"],
["hsmc_40",		"hc_aud_adcdat"],
["hsmc_39", 	"hc_aud_xck"],
["hsmc_42",		"hc_id_i2cdat"],
["hsmc_41",		"hc_id_i2cscl"],
["hsmc_44", 		"hc_sd_cmd"],
["hsmc_43", 		"hc_ps2_clk"],
["hsmc_48", 		"hc_sd_dat"],
["hsmc_47", 		"hc_ps2_dat"],
["hsmc_54", 		"hc_vga_hs"],
["hsmc_53", 		"hc_sd_dat3"],
["hsmc_56", 		"hc_td_d0"],
["hsmc_55", 		"hc_vga_vs"],
["hsmc_60", 		"hc_td_d1"],
["hsmc_59", 		"hc_vga_blank"],
["hsmc_62", 		"hc_td_d2"],
["hsmc_61", 		"hc_vga_sync"],
["hsmc_66", 		"hc_td_d3"],
["hsmc_65", 		"hc_vga_data0"],
["hsmc_68", 		"hc_td_d4"],
["hsmc_67", 		"hc_vga_data1"],
["hsmc_72", 		"hc_td_d5"],
["hsmc_71", 		"hc_vga_data2"],
["hsmc_74", 		"hc_td_d6"],
["hsmc_73", 		"hc_vga_data3"],
["hsmc_78", 		"hc_td_d7"],
["hsmc_77", 		"hc_vga_data4"],
["hsmc_80", 		"hc_td_reset"],
["hsmc_79", 		"hc_vga_data5"],
["hsmc_84", 		"hc_td_vs"],
["hsmc_83", 		"hc_vga_data6"],
["hsmc_86", 		"hc_td_hs"],
["hsmc_85", 		"hc_vga_data7"],
["hsmc_90", 		"hc_rx_err"],
["hsmc_89", 		"hc_vga_data8"],
["hsmc_92", 		"hc_rx_crs"],
["hsmc_91", 		"hc_vga_data9"],
["hsmc_96", 		"hc_rx_clk"],
["hsmc_95", 		"hc_nclk"],
["hsmc_98", 		"hc_td_27mhz"],
["hsmc_97", 		"hc_vga_clock"],
["hsmc_102", 		"hc_rx_rxd0"],
["hsmc_101", 		"hc_sd_clk"],
["hsmc_104", 		"hc_rx_rxd1"],
["hsmc_103", 		"hc_aud_adclrck"],
["hsmc_110", 		"hc_rx_rxd2"],
["hsmc_109", 		"hc_aud_daclrck"],
["hsmc_108", 		"hc_rx_rxd3"],
["hsmc_107", 		"hc_aud_dacdat"],

["hsmc_114", 		"hc_rx_col"],
["hsmc_113", 		"hc_aud_bclk"],
["hsmc_116", 		"hc_rx_dv"],
["hsmc_115", 		"hc_uart_rxd"],

["hsmc_120", 		"hc_adc_busy"],
["hsmc_119", 		"hc_uart_txd"],
["hsmc_122", 		"hc_adc_dout"],
["hsmc_121", 		"hc_eth_reset_n"],

["hsmc_126", 		"hc_lcd_data3"],
["hsmc_125", 		"hc_tx_en"],
["hsmc_128", 		"hc_lcd_data4"],
["hsmc_127", 		"hc_txd0"],

["hsmc_132", 		"hc_vd"],
["hsmc_131", 		"hc_txd1"],
["hsmc_134", 		"hc_hd"],
["hsmc_133", 		"hc_txd2"],

["hsmc_138", 		"hc_den"],
["hsmc_137", 		"hc_txd3"],
["hsmc_140", 		"hc_grest"],
["hsmc_139", 		"hc_mdc"],

["hsmc_144", 		"hc_scen"],
["hsmc_143", 		"hc_adc_cs_n"],
["hsmc_146", 		"hc_lcd_data5"],
["hsmc_145", 		"hc_lcd_data0"],

["hsmc_150", 		"hc_lcd_data6"],
["hsmc_149", 		"hc_lcd_data1"],
["hsmc_152", 		"hc_lcd_data7"],
["hsmc_151", 		"hc_lcd_data2"],

["hsmc_156", 		"hc_adc_penirq_n"],
["hsmc_155", 		"hc_adc_din"],
["hsmc_158", 		"hc_tx_clk"],
["hsmc_157", 		"hc_adc_dclk"]]

soc_pins = dict(soc_pins)
soc_pins_rev = {v:k for k, v in soc_pins.items()}
soc_hsmc = dict(soc_hsmc)
soc_hsmc_rev = {v:k for k, v in soc_hsmc.items()}

for i in hsmc_mult:
	#print i
	hsmc_pin = i[0]
	hsmc_mult_pin_name = i[1]
	soc_pin_name = soc_hsmc_rev[i[0]]
	soc_pin = soc_pins_rev[soc_pin_name]
	
	#print soc_pin, hsmc_mult_pin_name
	qsf_assignment = "set_location_assignment %s -to top_%s" % (soc_pin.upper(), hsmc_mult_pin_name.upper())
	print qsf_assignment
